/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin.reviews.index'
import { Route as AdminReviewsCaseIdRouteImport } from './routes/admin.reviews.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReviewsRoute,
} as any)
const AdminReviewsCaseIdRoute = AdminReviewsCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AdminReviewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/reviews/$caseId': typeof AdminReviewsCaseIdRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reviews/$caseId': typeof AdminReviewsCaseIdRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/reviews': typeof AdminReviewsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/reviews/$caseId': typeof AdminReviewsCaseIdRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/catalog'
    | '/admin/reviews'
    | '/admin/'
    | '/admin/reviews/$caseId'
    | '/admin/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/catalog'
    | '/admin'
    | '/admin/reviews/$caseId'
    | '/admin/reviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/catalog'
    | '/admin/reviews'
    | '/admin/'
    | '/admin/reviews/$caseId'
    | '/admin/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminReviewsRoute
    }
    '/admin/reviews/$caseId': {
      id: '/admin/reviews/$caseId'
      path: '/$caseId'
      fullPath: '/admin/reviews/$caseId'
      preLoaderRoute: typeof AdminReviewsCaseIdRouteImport
      parentRoute: typeof AdminReviewsRoute
    }
  }
}

interface AdminReviewsRouteChildren {
  AdminReviewsCaseIdRoute: typeof AdminReviewsCaseIdRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
}

const AdminReviewsRouteChildren: AdminReviewsRouteChildren = {
  AdminReviewsCaseIdRoute: AdminReviewsCaseIdRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
}

const AdminReviewsRouteWithChildren = AdminReviewsRoute._addFileChildren(
  AdminReviewsRouteChildren,
)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminReviewsRoute: typeof AdminReviewsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminReviewsRoute: AdminReviewsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
